# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bf99f13f0b3fc51ea2a45622557c9960e3c7f03f6acc3d35e76dddd3db9b3e7b9a49b356bee80d95cc5c4a58252cd3ba48ddc2745986f75a3779a8375a370c4

test:
  secret_key_base: 3b9848362350eec5e54df0f8475599f81d6ecd078e73af84eae6cdde25ad15a1f5ea95f44ac261dc92f145849f8ec620ed63368c43be7093e59a3f102d26229d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
